enabled: true
ignoring-pattern: ^(MRE-[0-9]+ Automatically bump build number to [0-9]+)$
ignores-hash-anchored-lines: true
ignores-trailing-new-lines: true
types: # defaults using (feat|fix|docs|style|refactor|test|chore) types.
  - feat # feature
  - fix # bug fix
  - docs # documentation
  - style # formatting, missing semi colons, …
  - refactor #
  - test # when adding missing tests
  - chore # maintain
  - release
  - merge
  - tag
  - branch    
scope:
  required: false
  allows-ascii-punctuation: true
  