enabled: true
types: # defaults using (feat|fix|docs|style|refactor|test|chore) types.
  - feat # feature
  - fix # bug fix
  - docs # documentation
  - style # formatting, missing semi colons, …
  - refactor #
  - test # when adding missing tests
  - chore # maintain
scope:
  required: false
  allows-ascii-punctuation: true
